### ISSUE TITLE
0 doesn't mean 0 on pre-order time frame

### ISSUE THREAD

**Issue by Kaiiak321** [WanderingDaniel/BookingNinjaTracker#24]
When you select time frame as 0 on pre-orders it still cuts off at midnight, rather than the booking time. This means any customers that book in last minute on a day like NYE couldn't pre-order. This will be an issue for valentines day where tables of 2 will book in circa 5pm for an 8.30pm table and won't be able to preorder.

**Comment by WanderingDaniel** [comment]
Fixed with latest version, will push tonight.
