### ISSUE TITLE
exit button needed

### ISSUE THREAD

**Issue by Kaiiak321** [WanderingDaniel/BookingNinjaTracker#28]
There is no escape from this screen, you have to click on Gannt which can result in you accidentally starting a new booking, which then doesn't disappear which means you need to refresh your screen which makes life slow and clunky. RED X BOX NEEDED

**Comment by WanderingDaniel** [comment]
Added in 9th build. Sent to QA for deployment tonight.

**Comment by Kaiiak321** [comment]
Hi dan, when is the deployment scheduled?
