### ISSUE TITLE
pre-orders still not allowing ppl to order on the day

### ISSUE THREAD

**Issue by Kaiiak321** [WanderingDaniel/BookingNinjaTracker#35]
https://letsbookfor.com/summat-to-ate/preorder/SfS8Fkaz2LbyLpaY

This is tonights booking and they can't preorder

**Comment by Kaiiak321** [comment]
This is still an issue....

**Comment by WanderingDaniel** [comment]
0 Days will now allow pre-orders up until the actual booking start time.
