### ISSUE TITLE
Bookings of more than 6 not working on some devices

### ISSUE THREAD

**Issue by Kaiiak321** [WanderingDaniel/BookingNinjaTracker#37]
Some customers, not myself, are not able to get to the next screen, they type 10 guests in the box and no continue box displays... this means they can not complete the booking. As I say I can't replicate this issue but two customers tonight have rang explaining the exact same issue.

This means for some customers we can not take large bookings. Please can you look into this?

**Comment by Kaiiak321** [comment]
Guests are saying that the continue button does load, but after a significant period of time, up to two minutes

**Comment by WanderingDaniel** [comment]
This isn't a bug; 

When the user selects a number of guest they have to leave the number field before it sends the update (to avoid excessive requests). I've changed it so after 1 second it will send however.

**Comment by Kaiiak321** [comment]
Perfect. Seems weird to have issues with this yesterday only and two of them… hopefully now resolvedOn 13 Feb 2024, at 15:34, WanderingDaniel ***@***.***> wrote:﻿
This isn't a bug;
When the user selects a number of guest they have to leave the number field before it sends the update (to avoid excessive requests). I've changed it so after 1 second it will send however.

**Comment by WanderingDaniel** [comment]
The randomness of the world I suspect! No changes were deployed on these areas for at least the last week. :)
