### ISSUE TITLE
Table merging

### ISSUE THREAD

**Issue by Kaiiak321** [WanderingDaniel/BookingNinjaTracker#6]
You used to be able to collapse a table chain. example table of 4 is on table 6+7 but now i can move it to table 10, drag the duplicate on top of ten and it will delete one table. currently have to edit booking click delete table... too clunky

**Comment by WanderingDaniel** [comment]
I've reinstated this functionality - hopefully with 20% less Jank :P 

I've also added the ability to split a booking into two when using a desktop (holding down Shift while dragging a booking will keep it on it's original table, AND add a new table)

**Comment by Kaiiak321** [comment]
This works! And its amazing!
