### ISSUE TITLE
previous/next day tabs

### ISSUE THREAD

**Issue by Kaiiak321** [WanderingDaniel/BookingNinjaTracker#7]
If these are staying at the top they need swapping as logivally in wrong order

**Comment by WanderingDaniel** [comment]
I think logically they will return to the side; as vertical space is more in demand that horizontal. They kinda got up there by accident :P

**Comment by Kaiiak321** [comment]
I think we agree here.. we weren't keen at them being on top but was unsure if it was to stop screen jumpyness between days

**Comment by WanderingDaniel** [comment]
I've set the side tabs to the, er, side. I've also got the bar floating so it moves with the scroll (and uses slightly less space as a result).
